app.task.not.found=Task with id {0} not found
user.exists=User with employee id {0} already exists.
project.exists=Project with name {0} already exists.
task.exists=Task with name {0} already exists.
parent.task.not.found=Parent Task with id {0} not found.
unexpected.internal.error=Somethings not right, please try again later.